
server:
  port: 8888

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp10u0e93427wkp4ako.mysql.rds.aliyuncs.com:3306/yicbridge_app_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: yicbridge
    password: yicbridge

#mybatis:
#  type-aliases-package: com.security.demo.entity
#  mapper-locations: classpath:mapper/**.xml
#
#mapper:
#  mappers: com.security.demo.dao.TkMapper
#  not-empty: false
#  identity: MYSQL
