
server:
  port: 8888

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp10u0e93427wkp4ako.mysql.rds.aliyuncs.com:3306/yicbridge_app_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: yicbridge
    password: yicbridge

  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 12
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 8
        max-wait: -1
jwt:
  header: token

#mybatis:
#  type-aliases-package: com.security.demo.entity
#  mapper-locations: classpath:mapper/**.xml
#
#mapper:
#  mappers: com.security.demo.dao.TkMapper
#  not-empty: false
#  identity: MYSQL
