package com.security.demo.entity;


import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `id`
    自增主键
     *
     * @boost.generated
     */
    private Long id;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `is_sender`
    是否云信默认发送者（用于发送时无法提供发送者）
1工作通知发送者
2系统通知发送者
...
     *
     * @boost.generated
     */
    private Integer isSender;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `sync_state`
    与第三方同步状态1已同步0未同步
     *
     * @boost.generated
     */
    private Integer syncState;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `user_or_person`
    用户或人员: 0用户; 1人员
     *
     * @boost.generated
     */
    private String userOrPerson;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `user_type`
    用戶类型1网易云信2钉钉用户
     *
     * @boost.generated
     */
    private Integer userType;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `person_type`
    人员类型: 0起重机安装人员
     *
     * @boost.generated
     */
    private String personType;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `real_name`
    真实姓名
     *
     * @boost.generated
     */
    private String realName;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `position`
    职位
     *
     * @boost.generated
     */
    private String position;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `position_dic_id`
    职位，字典表dic_code,dic_type确定唯一值
     *
     * @boost.generated
     */
    private Integer positionDicId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `mobile`
    手机
     *
     * @boost.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `email`
    邮箱
     *
     * @boost.generated
     */
    private String email;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `icon`
    头像地址
     *
     * @boost.generated
     */
    private String icon;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `sign`
    签名
     *
     * @boost.generated
     */
    private String sign;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `birth`
    生日
     *
     * @boost.generated
     */
    private String birth;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `gender`
    性别 0表示未知，1表示男，2表示女
     *
     * @boost.generated
     */
    private String gender;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `state`
    1有效0失效
     *
     * @boost.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `user_name`
    用户账号
     *
     * @boost.generated
     */
    private String userName;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `password`
    用户密码
     *
     * @boost.generated
     */
    private String password;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `active`
    是否激活钉钉
     *
     * @boost.generated
     */
    private Boolean active;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `accid`
    网易云信ID
     *
     * @boost.generated
     */
    private String accid;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `show_page`
    app默认展示页面
     *
     * @boost.generated
     */
    private Integer showPage;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `nickname`
    网易云通信ID昵称，最大长度64字符，用来PUSH推送
            昵称，用来PUSH推送
            昵称，用来PUSH推送时显示的昵称
     *
     * @boost.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `token`
    云信登录密码
     *
     * @boost.generated
     */
    private String token;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `ex`
    名片扩展字段建议封装成JSON字符串
     *
     * @boost.generated
     */
    private String ex;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `court_id`
    机构id
     *
     * @boost.generated
     */
    private Long courtId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `props`
    json属性，第三方可选填，最大长度1024字符
     *
     * @boost.generated
     */
    private String props;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `update_user_id`
    更新人
     *
     * @boost.generated
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `update_time`
    更新时间
     *
     * @boost.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `create_user_id`
    第三方用户ID
     *
     * @boost.generated
     */
    private Long createUserId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `create_time`
    创建时间
     *
     * @boost.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `third_party_user_id`
    第三放用户ID
     *
     * @boost.generated
     */
    private String thirdPartyUserId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `area_code`
    行政编码
     *
     * @boost.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `land_tel`
    座机号码
     *
     * @boost.generated
     */
    private String landTel;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `superior_user_id`
    直属上级

     *
     * @boost.generated
     */
    private Long superiorUserId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `short_tel`
    短号
     *
     * @boost.generated
     */
    private String shortTel;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `role_type`

     *
     * @boost.generated
     */
    private Integer roleType;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `id_card`
    身份证
     *
     * @boost.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `if_external`
    1内部0外部
     *
     * @boost.generated
     */
    private String ifExternal;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `photo_oss_key`
    电子照osskey
     *
     * @boost.generated
     */
    private String photoOssKey;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `in_staff`
    是否编内人员
     *
     * @boost.generated
     */
    private Integer inStaff;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `secret_related`
    是否涉密人员
     *
     * @boost.generated
     */
    private Integer secretRelated;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `gesture_password`
    手势密码
     *
     * @boost.generated
     */
    private String gesturePassword;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `gesture_password_active`
    是否开启手势密码/0 不开启，1开启
     *
     * @boost.generated
     */
    private Integer gesturePasswordActive;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `mobile_flag`
    手机号显示标识1显示0隐藏
     *
     * @boost.generated
     */
    private Integer mobileFlag;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `short_tel_flag`
    手机号显示标识1显示0隐藏
     *
     * @boost.generated
     */
    private Integer shortTelFlag;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `data_access`
    数据权限 myself，dept，court，all
     *
     * @boost.generated
     */
    private String dataAccess;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `order_sort`
    排序
     *
     * @boost.generated
     */
    private Integer orderSort;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `default_account`
    是否是该企业默认账户，1是，0否
     *
     * @boost.generated
     */
    private Integer defaultAccount;

    /**
     * 1启用0禁用
     */
    private Integer activeType;

    /**
     * This field was generated by Boost Generator.
     * This field corresponds to the database table yj_users
     *
     * @boost.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.id
     *
     * @return the value of yj_users.id
     *
     * @boost.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.id
     *
     * @param id the value for yj_users.id
     *
     * @boost.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.is_sender
     *
     * @return the value of yj_users.is_sender
     *
     * @boost.generated
     */
    public Integer getIsSender() {
        return isSender;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withIsSender(Integer isSender) {
        this.setIsSender(isSender);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.is_sender
     *
     * @param isSender the value for yj_users.is_sender
     *
     * @boost.generated
     */
    public void setIsSender(Integer isSender) {
        this.isSender = isSender;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.sync_state
     *
     * @return the value of yj_users.sync_state
     *
     * @boost.generated
     */
    public Integer getSyncState() {
        return syncState;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withSyncState(Integer syncState) {
        this.setSyncState(syncState);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.sync_state
     *
     * @param syncState the value for yj_users.sync_state
     *
     * @boost.generated
     */
    public void setSyncState(Integer syncState) {
        this.syncState = syncState;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.user_or_person
     *
     * @return the value of yj_users.user_or_person
     *
     * @boost.generated
     */
    public String getUserOrPerson() {
        return userOrPerson;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withUserOrPerson(String userOrPerson) {
        this.setUserOrPerson(userOrPerson);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.user_or_person
     *
     * @param userOrPerson the value for yj_users.user_or_person
     *
     * @boost.generated
     */
    public void setUserOrPerson(String userOrPerson) {
        this.userOrPerson = userOrPerson == null ? null : userOrPerson.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.user_type
     *
     * @return the value of yj_users.user_type
     *
     * @boost.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withUserType(Integer userType) {
        this.setUserType(userType);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.user_type
     *
     * @param userType the value for yj_users.user_type
     *
     * @boost.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.person_type
     *
     * @return the value of yj_users.person_type
     *
     * @boost.generated
     */
    public String getPersonType() {
        return personType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withPersonType(String personType) {
        this.setPersonType(personType);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.person_type
     *
     * @param personType the value for yj_users.person_type
     *
     * @boost.generated
     */
    public void setPersonType(String personType) {
        this.personType = personType == null ? null : personType.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.real_name
     *
     * @return the value of yj_users.real_name
     *
     * @boost.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withRealName(String realName) {
        this.setRealName(realName);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.real_name
     *
     * @param realName the value for yj_users.real_name
     *
     * @boost.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.position
     *
     * @return the value of yj_users.position
     *
     * @boost.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withPosition(String position) {
        this.setPosition(position);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.position
     *
     * @param position the value for yj_users.position
     *
     * @boost.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.position_dic_id
     *
     * @return the value of yj_users.position_dic_id
     *
     * @boost.generated
     */
    public Integer getPositionDicId() {
        return positionDicId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withPositionDicId(Integer positionDicId) {
        this.setPositionDicId(positionDicId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.position_dic_id
     *
     * @param positionDicId the value for yj_users.position_dic_id
     *
     * @boost.generated
     */
    public void setPositionDicId(Integer positionDicId) {
        this.positionDicId = positionDicId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.mobile
     *
     * @return the value of yj_users.mobile
     *
     * @boost.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withMobile(String mobile) {
        this.setMobile(mobile);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.mobile
     *
     * @param mobile the value for yj_users.mobile
     *
     * @boost.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.email
     *
     * @return the value of yj_users.email
     *
     * @boost.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.email
     *
     * @param email the value for yj_users.email
     *
     * @boost.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.icon
     *
     * @return the value of yj_users.icon
     *
     * @boost.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withIcon(String icon) {
        this.setIcon(icon);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.icon
     *
     * @param icon the value for yj_users.icon
     *
     * @boost.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.sign
     *
     * @return the value of yj_users.sign
     *
     * @boost.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withSign(String sign) {
        this.setSign(sign);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.sign
     *
     * @param sign the value for yj_users.sign
     *
     * @boost.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.birth
     *
     * @return the value of yj_users.birth
     *
     * @boost.generated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withBirth(String birth) {
        this.setBirth(birth);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.birth
     *
     * @param birth the value for yj_users.birth
     *
     * @boost.generated
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.gender
     *
     * @return the value of yj_users.gender
     *
     * @boost.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withGender(String gender) {
        this.setGender(gender);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.gender
     *
     * @param gender the value for yj_users.gender
     *
     * @boost.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.state
     *
     * @return the value of yj_users.state
     *
     * @boost.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withState(Integer state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.state
     *
     * @param state the value for yj_users.state
     *
     * @boost.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.user_name
     *
     * @return the value of yj_users.user_name
     *
     * @boost.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withUserName(String userName) {
        this.setUserName(userName);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.user_name
     *
     * @param userName the value for yj_users.user_name
     *
     * @boost.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.password
     *
     * @return the value of yj_users.password
     *
     * @boost.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.password
     *
     * @param password the value for yj_users.password
     *
     * @boost.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.active
     *
     * @return the value of yj_users.active
     *
     * @boost.generated
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withActive(Boolean active) {
        this.setActive(active);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.active
     *
     * @param active the value for yj_users.active
     *
     * @boost.generated
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.accid
     *
     * @return the value of yj_users.accid
     *
     * @boost.generated
     */
    public String getAccid() {
        return accid;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withAccid(String accid) {
        this.setAccid(accid);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.accid
     *
     * @param accid the value for yj_users.accid
     *
     * @boost.generated
     */
    public void setAccid(String accid) {
        this.accid = accid == null ? null : accid.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.show_page
     *
     * @return the value of yj_users.show_page
     *
     * @boost.generated
     */
    public Integer getShowPage() {
        return showPage;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withShowPage(Integer showPage) {
        this.setShowPage(showPage);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.show_page
     *
     * @param showPage the value for yj_users.show_page
     *
     * @boost.generated
     */
    public void setShowPage(Integer showPage) {
        this.showPage = showPage;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.nickname
     *
     * @return the value of yj_users.nickname
     *
     * @boost.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withNickname(String nickname) {
        this.setNickname(nickname);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.nickname
     *
     * @param nickname the value for yj_users.nickname
     *
     * @boost.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.token
     *
     * @return the value of yj_users.token
     *
     * @boost.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withToken(String token) {
        this.setToken(token);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.token
     *
     * @param token the value for yj_users.token
     *
     * @boost.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.ex
     *
     * @return the value of yj_users.ex
     *
     * @boost.generated
     */
    public String getEx() {
        return ex;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withEx(String ex) {
        this.setEx(ex);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.ex
     *
     * @param ex the value for yj_users.ex
     *
     * @boost.generated
     */
    public void setEx(String ex) {
        this.ex = ex == null ? null : ex.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.court_id
     *
     * @return the value of yj_users.court_id
     *
     * @boost.generated
     */
    public Long getCourtId() {
        return courtId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withCourtId(Long courtId) {
        this.setCourtId(courtId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.court_id
     *
     * @param courtId the value for yj_users.court_id
     *
     * @boost.generated
     */
    public void setCourtId(Long courtId) {
        this.courtId = courtId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.props
     *
     * @return the value of yj_users.props
     *
     * @boost.generated
     */
    public String getProps() {
        return props;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withProps(String props) {
        this.setProps(props);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.props
     *
     * @param props the value for yj_users.props
     *
     * @boost.generated
     */
    public void setProps(String props) {
        this.props = props == null ? null : props.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.update_user_id
     *
     * @return the value of yj_users.update_user_id
     *
     * @boost.generated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withUpdateUserId(Long updateUserId) {
        this.setUpdateUserId(updateUserId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.update_user_id
     *
     * @param updateUserId the value for yj_users.update_user_id
     *
     * @boost.generated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.update_time
     *
     * @return the value of yj_users.update_time
     *
     * @boost.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.update_time
     *
     * @param updateTime the value for yj_users.update_time
     *
     * @boost.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.create_user_id
     *
     * @return the value of yj_users.create_user_id
     *
     * @boost.generated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withCreateUserId(Long createUserId) {
        this.setCreateUserId(createUserId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.create_user_id
     *
     * @param createUserId the value for yj_users.create_user_id
     *
     * @boost.generated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.create_time
     *
     * @return the value of yj_users.create_time
     *
     * @boost.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.create_time
     *
     * @param createTime the value for yj_users.create_time
     *
     * @boost.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.third_party_user_id
     *
     * @return the value of yj_users.third_party_user_id
     *
     * @boost.generated
     */
    public String getThirdPartyUserId() {
        return thirdPartyUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withThirdPartyUserId(String thirdPartyUserId) {
        this.setThirdPartyUserId(thirdPartyUserId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.third_party_user_id
     *
     * @param thirdPartyUserId the value for yj_users.third_party_user_id
     *
     * @boost.generated
     */
    public void setThirdPartyUserId(String thirdPartyUserId) {
        this.thirdPartyUserId = thirdPartyUserId == null ? null : thirdPartyUserId.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.area_code
     *
     * @return the value of yj_users.area_code
     *
     * @boost.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withAreaCode(String areaCode) {
        this.setAreaCode(areaCode);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.area_code
     *
     * @param areaCode the value for yj_users.area_code
     *
     * @boost.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.land_tel
     *
     * @return the value of yj_users.land_tel
     *
     * @boost.generated
     */
    public String getLandTel() {
        return landTel;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withLandTel(String landTel) {
        this.setLandTel(landTel);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.land_tel
     *
     * @param landTel the value for yj_users.land_tel
     *
     * @boost.generated
     */
    public void setLandTel(String landTel) {
        this.landTel = landTel == null ? null : landTel.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.superior_user_id
     *
     * @return the value of yj_users.superior_user_id
     *
     * @boost.generated
     */
    public Long getSuperiorUserId() {
        return superiorUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withSuperiorUserId(Long superiorUserId) {
        this.setSuperiorUserId(superiorUserId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.superior_user_id
     *
     * @param superiorUserId the value for yj_users.superior_user_id
     *
     * @boost.generated
     */
    public void setSuperiorUserId(Long superiorUserId) {
        this.superiorUserId = superiorUserId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.short_tel
     *
     * @return the value of yj_users.short_tel
     *
     * @boost.generated
     */
    public String getShortTel() {
        return shortTel;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withShortTel(String shortTel) {
        this.setShortTel(shortTel);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.short_tel
     *
     * @param shortTel the value for yj_users.short_tel
     *
     * @boost.generated
     */
    public void setShortTel(String shortTel) {
        this.shortTel = shortTel == null ? null : shortTel.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.role_type
     *
     * @return the value of yj_users.role_type
     *
     * @boost.generated
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withRoleType(Integer roleType) {
        this.setRoleType(roleType);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.role_type
     *
     * @param roleType the value for yj_users.role_type
     *
     * @boost.generated
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.id_card
     *
     * @return the value of yj_users.id_card
     *
     * @boost.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withIdCard(String idCard) {
        this.setIdCard(idCard);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.id_card
     *
     * @param idCard the value for yj_users.id_card
     *
     * @boost.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.if_external
     *
     * @return the value of yj_users.if_external
     *
     * @boost.generated
     */
    public String getIfExternal() {
        return ifExternal;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withIfExternal(String ifExternal) {
        this.setIfExternal(ifExternal);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.if_external
     *
     * @param ifExternal the value for yj_users.if_external
     *
     * @boost.generated
     */
    public void setIfExternal(String ifExternal) {
        this.ifExternal = ifExternal == null ? null : ifExternal.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.photo_oss_key
     *
     * @return the value of yj_users.photo_oss_key
     *
     * @boost.generated
     */
    public String getPhotoOssKey() {
        return photoOssKey;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withPhotoOssKey(String photoOssKey) {
        this.setPhotoOssKey(photoOssKey);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.photo_oss_key
     *
     * @param photoOssKey the value for yj_users.photo_oss_key
     *
     * @boost.generated
     */
    public void setPhotoOssKey(String photoOssKey) {
        this.photoOssKey = photoOssKey == null ? null : photoOssKey.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.in_staff
     *
     * @return the value of yj_users.in_staff
     *
     * @boost.generated
     */
    public Integer getInStaff() {
        return inStaff;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withInStaff(Integer inStaff) {
        this.setInStaff(inStaff);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.in_staff
     *
     * @param inStaff the value for yj_users.in_staff
     *
     * @boost.generated
     */
    public void setInStaff(Integer inStaff) {
        this.inStaff = inStaff;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.secret_related
     *
     * @return the value of yj_users.secret_related
     *
     * @boost.generated
     */
    public Integer getSecretRelated() {
        return secretRelated;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withSecretRelated(Integer secretRelated) {
        this.setSecretRelated(secretRelated);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.secret_related
     *
     * @param secretRelated the value for yj_users.secret_related
     *
     * @boost.generated
     */
    public void setSecretRelated(Integer secretRelated) {
        this.secretRelated = secretRelated;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.gesture_password
     *
     * @return the value of yj_users.gesture_password
     *
     * @boost.generated
     */
    public String getGesturePassword() {
        return gesturePassword;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withGesturePassword(String gesturePassword) {
        this.setGesturePassword(gesturePassword);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.gesture_password
     *
     * @param gesturePassword the value for yj_users.gesture_password
     *
     * @boost.generated
     */
    public void setGesturePassword(String gesturePassword) {
        this.gesturePassword = gesturePassword == null ? null : gesturePassword.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.gesture_password_active
     *
     * @return the value of yj_users.gesture_password_active
     *
     * @boost.generated
     */
    public Integer getGesturePasswordActive() {
        return gesturePasswordActive;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withGesturePasswordActive(Integer gesturePasswordActive) {
        this.setGesturePasswordActive(gesturePasswordActive);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.gesture_password_active
     *
     * @param gesturePasswordActive the value for yj_users.gesture_password_active
     *
     * @boost.generated
     */
    public void setGesturePasswordActive(Integer gesturePasswordActive) {
        this.gesturePasswordActive = gesturePasswordActive;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.mobile_flag
     *
     * @return the value of yj_users.mobile_flag
     *
     * @boost.generated
     */
    public Integer getMobileFlag() {
        return mobileFlag;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withMobileFlag(Integer mobileFlag) {
        this.setMobileFlag(mobileFlag);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.mobile_flag
     *
     * @param mobileFlag the value for yj_users.mobile_flag
     *
     * @boost.generated
     */
    public void setMobileFlag(Integer mobileFlag) {
        this.mobileFlag = mobileFlag;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.short_tel_flag
     *
     * @return the value of yj_users.short_tel_flag
     *
     * @boost.generated
     */
    public Integer getShortTelFlag() {
        return shortTelFlag;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withShortTelFlag(Integer shortTelFlag) {
        this.setShortTelFlag(shortTelFlag);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.short_tel_flag
     *
     * @param shortTelFlag the value for yj_users.short_tel_flag
     *
     * @boost.generated
     */
    public void setShortTelFlag(Integer shortTelFlag) {
        this.shortTelFlag = shortTelFlag;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.data_access
     *
     * @return the value of yj_users.data_access
     *
     * @boost.generated
     */
    public String getDataAccess() {
        return dataAccess;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withDataAccess(String dataAccess) {
        this.setDataAccess(dataAccess);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.data_access
     *
     * @param dataAccess the value for yj_users.data_access
     *
     * @boost.generated
     */
    public void setDataAccess(String dataAccess) {
        this.dataAccess = dataAccess == null ? null : dataAccess.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.order_sort
     *
     * @return the value of yj_users.order_sort
     *
     * @boost.generated
     */
    public Integer getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withOrderSort(Integer orderSort) {
        this.setOrderSort(orderSort);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.order_sort
     *
     * @param orderSort the value for yj_users.order_sort
     *
     * @boost.generated
     */
    public void setOrderSort(Integer orderSort) {
        this.orderSort = orderSort;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_users.default_account
     *
     * @return the value of yj_users.default_account
     *
     * @boost.generated
     */
    public Integer getDefaultAccount() {
        return defaultAccount;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    public User withDefaultAccount(Integer defaultAccount) {
        this.setDefaultAccount(defaultAccount);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_users.default_account
     *
     * @param defaultAccount the value for yj_users.default_account
     *
     * @boost.generated
     */
    public void setDefaultAccount(Integer defaultAccount) {
        this.defaultAccount = defaultAccount;
    }

    public Integer getActiveType() {
        return activeType;
    }

    public User withActiveType(Integer activeType) {
        this.setActiveType(activeType);
        return this;
    }

    public void setActiveType(Integer activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_users
     *
     * @boost.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isSender=").append(isSender);
        sb.append(", syncState=").append(syncState);
        sb.append(", userOrPerson=").append(userOrPerson);
        sb.append(", userType=").append(userType);
        sb.append(", personType=").append(personType);
        sb.append(", realName=").append(realName);
        sb.append(", position=").append(position);
        sb.append(", positionDicId=").append(positionDicId);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", icon=").append(icon);
        sb.append(", sign=").append(sign);
        sb.append(", birth=").append(birth);
        sb.append(", gender=").append(gender);
        sb.append(", state=").append(state);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", active=").append(active);
        sb.append(", accid=").append(accid);
        sb.append(", showPage=").append(showPage);
        sb.append(", nickname=").append(nickname);
        sb.append(", token=").append(token);
        sb.append(", ex=").append(ex);
        sb.append(", courtId=").append(courtId);
        sb.append(", props=").append(props);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", thirdPartyUserId=").append(thirdPartyUserId);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", landTel=").append(landTel);
        sb.append(", superiorUserId=").append(superiorUserId);
        sb.append(", shortTel=").append(shortTel);
        sb.append(", roleType=").append(roleType);
        sb.append(", idCard=").append(idCard);
        sb.append(", ifExternal=").append(ifExternal);
        sb.append(", photoOssKey=").append(photoOssKey);
        sb.append(", inStaff=").append(inStaff);
        sb.append(", secretRelated=").append(secretRelated);
        sb.append(", gesturePassword=").append(gesturePassword);
        sb.append(", gesturePasswordActive=").append(gesturePasswordActive);
        sb.append(", mobileFlag=").append(mobileFlag);
        sb.append(", shortTelFlag=").append(shortTelFlag);
        sb.append(", dataAccess=").append(dataAccess);
        sb.append(", orderSort=").append(orderSort);
        sb.append(", defaultAccount=").append(defaultAccount);
        sb.append(", activeType=").append(activeType);
        sb.append("]");
        return sb.toString();
    }
}